// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqnTvC86TEhKbba7mvIDmz-lGONwGs70',
    appId: '1:488526388553:web:aace1e7889ca5fbbe80e98',
    messagingSenderId: '488526388553',
    projectId: 'crud-test-13167',
    authDomain: 'crud-test-13167.firebaseapp.com',
    storageBucket: 'crud-test-13167.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXE2FmKlgj6NpdPl-UVzbLgSDvhGe3gcM',
    appId: '1:488526388553:android:82fbee4a3ca76d72e80e98',
    messagingSenderId: '488526388553',
    projectId: 'crud-test-13167',
    storageBucket: 'crud-test-13167.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrqnTvC86TEhKbba7mvIDmz-lGONwGs70',
    appId: '1:488526388553:web:5cf50b43751854e9e80e98',
    messagingSenderId: '488526388553',
    projectId: 'crud-test-13167',
    authDomain: 'crud-test-13167.firebaseapp.com',
    storageBucket: 'crud-test-13167.firebasestorage.app',
  );
}
